Add colors to the tui monitor view
hatoo/oha pull request #187
Opened 2022-09-11 10:25 UTC by wjhoward

I've really enjoyed using Oha, thank you for your hard work. 

This PR adds color to the main monitor view, using the Bang Wong color blind friendly palette. This can be optionally disabled using the `--disable-color` flag.

I did consider adding terminal capable color checks, e.g. checking `$COLORTERM` / `$TERM` environment variables, although this doesn't work for all platforms (e.g. Windows Powershell). All modern terminals will support colors, and I've tested this on MacOs - Iterm2 and Windows 10 Powershell ( I don't have an Ubuntu Gnome terminal to hand ).

![image](https://user-images.githubusercontent.com/61805721/189521709-ed64df9b-d455-4d4a-a933-e349b5a9a4d9.png)

I did consider adding color ranges to the printed latency output, as per issue: https://github.com/hatoo/oha/issues/64 but I hesitated, as latency ranges can vary considerably per application.

The README etc would need to be updated, but wanted to get your thoughts on the change first.

2022-09-11 11:30 UTC, hatoo commented
Great👍 
Please go ahead.
Don't forget to update `CHANGELOG.md`!

2022-09-11 17:39 UTC, wjhoward commented
Great, thanks! Do you want me to update the `demo.gif` also?

2022-09-12 02:42 UTC, hatoo commented
Yeah, if you update `demo.gif` also, it's very helpful.

2022-09-12 08:52 UTC, wjhoward commented
> Yeah, if you update `demo.gif` also, it's very helpful.

Added a new `demo.gif`, the dimensions are lower than the original, but this seems largely due to the fact I tried to keep the amount of detail the same in the gif using a small terminal window. If I draw a bigger window (with higher dimensions) I get much more detail, e.g. many more bars. It looks pretty good in the README, e.g. https://github.com/wjhoward/oha/tree/add-tui-colors

2022-09-12 11:41 UTC, wjhoward commented
Let me know if you want me to make any changes or add anything else before considering merging this? Thanks!

2022-09-12 13:11 UTC, hatoo requested changes

2022-09-12 13:11 UTC, hatoo commented on src/monitor.rs
> +        let mut colors: HashMap<&'static str, Color> = HashMap::new();
I prefer to use a custom struct for the color scheme instead of `HashMap` to avoid typo for a color.

This would looks like
```rust
struct ColorScheme {
    light_blue: Option<Color>,
    ...
}

let colors = ColorScheme {
    light_blue: ...
};

// use a color
colors.light_blue.unwrap_or(...)
```

2022-09-12 13:11 UTC, hatoo commented on CHANGELOG.md
> +# 0.5.5 (2022-09-12)
Please remove this line.
I'll add this line when we release a new version

2022-09-12 13:12 UTC, hatoo commented
Sorry, I thought I added a review yesterday but it was `pending` state.
I've added reviews now, could you see my reviews?

2022-09-12 13:47 UTC, wjhoward commented
> Sorry, I thought I added a review yesterday but it was `pending` state. I've added reviews now, could you see my reviews?

No problem! I can see the review now, will make the required changes shortly. Thanks

2022-09-13 06:05 UTC, hatoo approved these changes

2022-09-13 06:05 UTC, merged

2022-09-13 06:06 UTC, hatoo commented
Thanks! merged.

2023-02-08 04:52 UTC, Vanav commented
I don't see colors in tui for some reason: 
![image](https://user-images.githubusercontent.com/761333/217436027-44a82963-121c-4339-8882-c22953ffb49f.png)
Also notice that progress bar is invisible in "color" mode.

oha v0.5.6 (amd64 build from Releases page), Ubuntu 22 / Debian 11, TERM=xterm-256color.
Ternimal has no issues with colors, even oha shows some: 
![image](https://user-images.githubusercontent.com/761333/217436439-f34b08d5-bf93-4e2b-9e33-a4e6bb5c3979.png)