Add containerfile for oha
hatoo/oha pull request #345
Opened 2023-12-11 19:07 UTC by tonyskapunk

Useful to build and run oha wihtout Rust tooling installed locally.

2023-12-12 06:36 UTC, hatoo requested changes
Thank you!

Dockerfile looks good!
Please add `.dockerignore` to ignore `target` directory and add some short usage to README.md?

2023-12-12 22:05 UTC, tonyskapunk commented
README is now updated, let me know what you think, thanks!

2023-12-13 06:40 UTC, hatoo approved these changes

2023-12-13 06:40 UTC, merged

2023-12-13 06:40 UTC, hatoo commented
Great, thank you!